### ISSUE TITLE
[QUESTION] 用户名.txt 在下载主页后缺失。

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/f2#202]
**问题描述**
下载用户主页视频后不会在下载文件夹内生成带有用户URL的, 以用户名为文件名的.txt 文件。

**其他细节**
在0.0.1.5的版本中，程序会在用户文件夹内生成以用户名为文件名的.txt文件。内含有用户主页的HTTPS URL链接。
但在0.0.1.6的版本中，尝试下载时，.txt文件无法被发现了

**期望的支持**

- 通过某些方法使得.txt文件可以再次被生成。
    - 如何通过修改程序文件来再次支持用户的.txt文件生成（若可实现）

**其他**
版本：0.0.1.6
app.yaml:
```
douyin:
  cookies: ###
  cover: no
  desc: no
  folderize: no
  music: no
  lyric: no
  max_connections: 32
  max_counts: 0
  max_retries: 10
  max_tasks: 2
  page_counts: 20
  timeout: 15
  interval: 'all'
  path: Z:\TT DI
  naming: '{create}'
  mode: post
```
