### ISSUE TITLE
[QUESTION]是不是我姿势不太对呢，第n次响应为空

### ISSUE THREAD

**Issue by joisun** [Johnserf-Seed/f2#208]
**问题描述**
**我的配置：**
```bash
douyin:
  cookie: douyin.com; xg_d..............................very long 很长省略.............................221%22
  naming: "{create}_{desc}"
  path: .
  timeout: 10
  max_retries: 5
  lyric: yes
  max_connections: 5
  max_counts: 0
  max_tasks: 10
  page_counts: 20
```
**我执行的命令：**
```bash
f2 dy -c app.yaml  -M one -u "https://v.douyin.com/iDDtcx22/"
```
**我做过的尝试**
我是 wsl-ubuntu 环境, 不知道为什么，我配置的 windows Chrome 环境变量不起作用，所以我没办法使用 [文档#配置cookie](https://johnserf-seed.github.io/f2/site-config.html#%E9%85%8D%E7%BD%AEcookie) 中的自动配置 cookie , 我使用的是手动获取的 document.cookie 方式。

![image](https://github.com/user-attachments/assets/3dd6a7f4-f6ca-4ff0-a83b-c2ab8c48f7a6)

**Comment by joisun** [comment]
> [#193 (comment)](https://github.com/Johnserf-Seed/f2/issues/193#issuecomment-2490225119)

谢谢你的帮助， 不过我就是手动填写的 cookie

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/3a923ded-c4b4-4e1d-975b-374a7a85d886)
我测试了可以采集，所以问题出在cookie上，单一作品的接口控登录的cookie，更新一下新的再尝试看看

**Comment by joisun** [comment]
> ![image](https://private-user-images.githubusercontent.com/40727745/390435844-3a923ded-c4b4-4e1d-975b-374a7a85d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTYwMzQsIm5iZiI6MTczMjcxNTczNCwicGF0aCI6Ii80MDcyNzc0NS8zOTA0MzU4NDQtM2E5MjNkZWQtYzRiNC00ZTFkLTk3NWItMzc0YTdhODVkODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEzNTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MzgxZjExYzUyZTQ4MTVjNDliYmM3OWNkN2VlNDEzNmFiOTY1Y2M2YzdkZGI2YTA5NGViOGRiZTg5OTgyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I9dR1x3lc0nyEgaUvrBCIs0nlmSuvZlXEeGCMPkQKjQ) 我测试了可以采集，所以问题出在cookie上，单一作品的接口控登录的cookie，更新一下新的再尝试看看

我更新了好些次了， 可能是我的方式不对？ 另外，和这个应该没有关系的对吧
![image](https://github.com/user-attachments/assets/17e7a3fe-2818-4204-a71c-62bb6d1f1de6)

可能是我cookie 的获取和填写有些问题吗？我是这样更新的：
1. 打开抖音网页版本，登陆后， console 控制台 输入 document.cookie 后复制 文本内容
2. 粘贴到 我的 app.yaml - douyin - cookie 字段， 这是我的 app.yaml 的完整配置：

```yaml
douyin:
  cookie: douyin.com; xg_device_score=7.664966583511937; device_web_cpu_core=16; device_web_memory_size=8; architecture=amd64; bd_ticket_guard_client_web_domain=2; SEARCH_RESULT_LIST_TYPE=%22single%22; UIFID_TEMP=3c3e9d4a635845249e00419877a3730e2149197a63ddb1d8525033ea2b3354c2fa73328e71b80937770671b2477dbe1c0bfb214d773a3484e27a4a1ac1ecf3ce3f40f4e91c610ff5180252f6e8aaa893; fpk1=U2FsdGVkX19thdluxCIxF652nPyDNaZO2kAnNvHAgBgCwRJTi/CimK8YDVOr0rbz2UGLNMkCrA9lCfvGO3hkfA==; fpk2=f1f6b29a6cc1f79a0fea05b885aa33d0; UIFID=3c3e9d4a635845249e00419877a3730e2149197a63ddb1d8525033ea2b3354c2fa73328e71b80937770671b2477dbe1c92e491fd1cc3fa2ec50da73bc43eb48618dec31e62762c8cf3f700b9f8bc7aa32a5dc7eb030ce7ac1b0a21502fcab1845e1af03b5930fdd3f230af5116fc76d983c0dc4ba18d28c090fb208a8f5e15ff5c4b33d346ecf9b787291f04581198409d529cd697000887c8c8a33e3417319f; hevc_supported=true; passport_assist_user=Cjxwcx8Odp6bi9QZ_tQ8Y1CBNl-1APRTLU3xs43HIzYPvqB6QKWsIYXwRyOJwdT0o3ZK7sSF0n1erp7uyW8aSgo8e6x8anDxBAB0L4T2Mvbt_CyuBB9uAU8U7WAIX07bp2HN2-GBX0nkv_kYI4uoB6BywL4fMWAhJ8A-1sKBEIaE2w0Yia_WVCABIgEDzy7jhQ%3D%3D; s_v_web_id=verify_m24m1wvi_ALedMxEr_MbSB_4PzG_Akjb_hkmORf0ylIBh; passport_csrf_token=268ad95e27592b9449c262a2b99e3b7f; passport_csrf_token_default=268ad95e27592b9449c262a2b99e3b7f; SelfTabRedDotControl=%5B%7B%22id%22%3A%227189611185321281592%22%2C%22u%22%3A34%2C%22c%22%3A0%7D%2C%7B%22id%22%3A%227212248302945830971%22%2C%22u%22%3A35%2C%22c%22%3A0%7D%5D; __live_version__=%221.1.2.5201%22; live_use_vvc=%22false%22; dy_swidth=1920; dy_sheight=1080; csrf_session_id=1459aa8cd7eb4898f41b73a035be35de; strategyABtestKey=%221732697271.785%22; biz_trace_id=287b80b3; is_dash_user=1; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.5%7D; publish_badge_show_info=%220%2C0%2C0%2C1732697273937%22; pwa2=%220%7C0%7C1%7C0%22; WallpaperGuide=%7B%22showTime%22%3A0%2C%22closeTime%22%3A0%2C%22showCount%22%3A0%2C%22cursor1%22%3A10%2C%22cursor2%22%3A2%7D; download_guide=%220%2F%2F1%22; __ac_nonce=06747213300257dce1ee3; __ac_signature=_02B4Z6wo00f01kPFaQQAAIDCyZFnzkH6iu5D5W2AAPfF2b; IsDouyinActive=true; home_can_add_dy_2_desktop=%220%22; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A16%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A6.95%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A100%7D%22; FOLLOW_LIVE_POINT_INFO=%22MS4wLjABAAAARh508UPH5rVXl-CkyNOdu56noPTxhqWUFEf1UB0Fbeg%2F1732723200000%2F0%2F0%2F1732715408585%22; FOLLOW_NUMBER_YELLOW_POINT_INFO=%22MS4wLjABAAAARh508UPH5rVXl-CkyNOdu56noPTxhqWUFEf1UB0Fbeg%2F1732723200000%2F0%2F0%2F1732716008585%22; passport_fe_beating_status=true; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCR2lxRWFGVnh6ajVvQzkwVk1CQ2pKZU9GUjErbUI2R0poVEVqM1BSaEg1UkEycGV3amVITFkrdHR1Z0Jmek5BMFowd3FBSE05Y3MrT2Y0M21wZWJZWGs9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoyfQ%3D%3D
  naming: "{create}_{desc}"
  path: .
  timeout: 10
  max_retries: 5
  lyric: yes
  max_connections: 5
  max_counts: 0
  max_tasks: 10
  page_counts: 20
  ```
  
  再次感谢大佬的时间。
