### ISSUE TITLE
部分下载配置不生效

### ISSUE THREAD

**Issue by junerver** [Johnserf-Seed/f2#22]
已经在yaml中配置了：
```yaml
  desc: false
  folderize: false
  music: false
```
但是下载后仍然将下载的作品保存到单独的文件夹，并下载了音乐、文本、封面等文件
