### ISSUE TITLE
[QUESTION] 下载抖音作者主页作品只能下载一页

### ISSUE THREAD

**Issue by Josoen** [Johnserf-Seed/f2#319]
- [ ] ~~*在提问时请注意不要包含个人敏感信息*~~
- [ ] 我明白我的提问可能不会得到明确回复或解决。

**问题描述**
最近突然出现的问题，下载抖音主页作品时，暂停十秒之后就直接显示已经下完所有作品（20个）

**其他细节**
在0.0.1.7上出现，手动安装最新的0.0.1.8-pw3问题依旧存在

**截图/代码示例**
配置文件: `dy.yaml`
```yaml
douyin:
  url: https://v.douyin.com/LhgHn7vOLcY/
  cookie: 省略
  cover: true
  desc: null
  folderize: false
  interval: all
  languages: null
  lyric: null
  max_connections: null
  max_counts: null
  max_retries: null
  max_tasks: null
  mode: post
  music: null
  naming: '{nickname}_{create}'
  #naming: '{nickname}_{create}_{desc}'
  page_counts: null
  path: /mnt/e/douyin_download/
  timeout: null
```
[测试的主页](https://www.douyin.com/user/MS4wLjABAAAAROX5yczvQA8AA2ZLucbe6Lgq725EMKJRUzrtTcA6-xE?from_tab_name=main&vid=7505288669206449467)有一百多作品

![Image](https://github.com/user-attachments/assets/58551c12-69e4-49dc-8386-30c05d45aa50)

**期望的支持**
简要说明你期望从社区或项目维护者那里得到的支持或回答。

**其他**
如果有其他需要补充的内容，请在此处添加。
